### ISSUE TITLE
dos2unix script for SLURM job file

### ISSUE THREAD

**Issue by Mys73** [harris-2374/srmjg#1]
Using a srmjg on a windows system results in incompatible script for job request and must be converted to linux code (from \r\n to just \n) using dos2unix command. 
Asking for similar script to "run_all_jobs.sh" script at end of job request generation to convert all job files to linux, or ensuring that the end job files are in the correct code.

**Comment by harris-2374** [comment]
Hi Mys73,

Thank you for pointing this out, I will correct this and let you know when I have pushed an update.

-Andrew

**Comment by harris-2374** [comment]
I just pushed an update that should resolve this issue. If you still run into the same issue, let me know.

Thanks
-Andrew
